language: node_js
node_js:
  - "node" # latest version
cache:
  directories:
    - node_modules
script:
  - npm run tests
  - npm run build
before_deploy:
  - cd functions && yarn install && cd ..
deploy:
  - provider: firebase
    project: "staging"
    token: $FIREBASE_STAGING_TOKEN
    skip_cleanup: true
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH != "master"
  - provider: firebase
    project: "production"
    token: $FIREBASE_PRODUCTION_TOKEN
    skip_cleanup: true
    on:
      branch: master
