language: node_js
node_js:
  - "node" # latest version
cache:
  yarn: true
  directories:
    - node_modules
script:
  - yarn build
deploy:
  provider: firebase
  token: $FIREBASE_TOKEN
  on:
    all_branches: true
